#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# run_gap_4gpu_resume.sh — re-run MISSING pair shards and merge into
# the existing output directory.
#
# Generated by: scripts/merge_gap_shards.py
#
# Worker layout (sequential within each node to avoid merge race):
#   mscluster107 GPU 0 : pairs 0–5
#   mscluster107 GPU 1 : pairs 6–11
#   mscluster109 GPU 0 : pairs 12–17
#   mscluster109 GPU 1 : pairs 18–23
#
# Usage:  bash scripts/run_gap_4gpu_resume.sh [OUTPUT_DIR]
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUTPUT_DIR="${1:-${ROOT_DIR}/results/gap_large_4gpu_rerun_2}"
CONDA_ENV="${CONDA_ENV:-jaxstack}"
CONDA_EXE="${CONDA_EXE:-${HOME}/miniforge3/bin/conda}"
EXTRA_ARGS="${EXTRA_ARGS:-}"
SEED_BATCH_SIZE="${SEED_BATCH_SIZE:-8}"
SLURM_PARTITION="${SLURM_PARTITION:-biggpu}"
SLURM_TIME="${SLURM_TIME:-72:00:00}"
SLURM_CPUS_PER_TASK="${SLURM_CPUS_PER_TASK:-8}"
LOG_DIR="${LOG_DIR:-${ROOT_DIR}/logs}"

mkdir -p "$OUTPUT_DIR"
mkdir -p "$LOG_DIR"

if [[ ! -x "$CONDA_EXE" ]]; then
    echo "Conda executable not found: $CONDA_EXE" >&2
    exit 1
fi

COMMON_ARGS=(
    --paper-only
    --regime large
    --pstar-source sdipc
    --model-family sd14
    --output-dir "$OUTPUT_DIR"
    --seed-batch-size "$SEED_BATCH_SIZE"
    --merge
)

if [[ -n "$EXTRA_ARGS" ]]; then
    # shellcheck disable=SC2206
    EXTRA_ARGS_ARRAY=($EXTRA_ARGS)
    COMMON_ARGS+=("${EXTRA_ARGS_ARRAY[@]}")
fi

SBATCH_COMMON=(
    --parsable
    --ntasks 1
    --cpus-per-task "$SLURM_CPUS_PER_TASK"
    --partition "$SLURM_PARTITION"
    --time "$SLURM_TIME"
)

# submit_node_job NODE PAIR0_START PAIR0_END PAIR1_START PAIR1_END
# Workers run SEQUENTIALLY within the node (gpu0 finishes before gpu1
# starts) to avoid concurrent writes to the shared aggregate JSON files.
submit_node_job() {
    local node=$1
    local pair0_start=$2
    local pair0_end=$3
    local pair1_start=$4
    local pair1_end=$5

    local job_name="gap-resume-${node}"
    local slurm_out="${LOG_DIR}/${job_name}-%j.out"
    local slurm_err="${LOG_DIR}/${job_name}-%j.err"

    sbatch \
        "${SBATCH_COMMON[@]}" \
        --job-name "$job_name" \
        --nodelist "$node" \
        --output "$slurm_out" \
        --error "$slurm_err" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

cd "$ROOT_DIR"
mkdir -p "$OUTPUT_DIR"

run_worker() {
    local gpu=$1
    local pair_start=$2
    local pair_end=$3
    [[ "$pair_start" -ge "$pair_end" ]] && return 0  # empty range
    local log_file="${OUTPUT_DIR}/worker_resume_${node}_gpu${gpu}.log"
    echo "[$(date '+%F %T')] ${node} gpu${gpu} pairs ${pair_start}-$((pair_end - 1)) (resume+merge)" | tee -a "$log_file"
    CUDA_VISIBLE_DEVICES="$gpu" USE_TF=0 \
        "$CONDA_EXE" run --no-capture-output -n "$CONDA_ENV" \
        python scripts/measure_composability_gap.py \
        ${COMMON_ARGS[*]} --pair-start "$pair_start" --pair-end "$pair_end" \
        >> "$log_file" 2>&1
}

# Sequential: GPU 0 first, then GPU 1.
# This prevents both workers from simultaneously overwriting the shared
# aggregate JSON files at the end of their runs.
run_worker 0 $pair0_start $pair0_end || { echo 'GPU 0 worker failed' >&2; exit 1; }
run_worker 1 $pair1_start $pair1_end || { echo 'GPU 1 worker failed' >&2; exit 1; }
EOF
}

echo "Output: $OUTPUT_DIR"
echo "Submitting 2 SLURM resume jobs (workers sequential within each node) ..."

JOB_107="$(submit_node_job mscluster107 0 6 6 12)"
JOB_109="$(submit_node_job mscluster109 12 18 18 24)"

echo "Submitted:"
echo "  mscluster107: GPU0 pairs 0-5, GPU1 pairs 6-11  (job ${JOB_107})"
echo "  mscluster109: GPU0 pairs 12-17, GPU1 pairs 18-23  (job ${JOB_109})"

echo ""
echo "Monitor with:"
echo "  squeue -u $USER"
echo "  tail -f ${OUTPUT_DIR}/worker_resume_mscluster107_gpu0.log"
echo "  tail -f ${OUTPUT_DIR}/worker_resume_mscluster107_gpu1.log"
echo "  tail -f ${OUTPUT_DIR}/worker_resume_mscluster109_gpu0.log"
echo "  tail -f ${OUTPUT_DIR}/worker_resume_mscluster109_gpu1.log"

echo ""
echo "After jobs finish, verify with:"
echo "  python scripts/merge_gap_shards.py --data-dir ${OUTPUT_DIR} --skip-all-pairs-gap"
