"""
SD35TextInverter
================
A text-outputting image inverter calibrated to SD3.5.

Given an image (generated by SD3.5 or SuperDiff-AND), produces a natural-
language string p* such that SD3.5(p*) approximately reconstructs the input.

Architecture
------------
- Backbone:  CLIP ViT-L/14 (frozen) → CLS feature (768-dim)
- Mapper:    MLP  768 → n_prefix × 768  (ClipCap-style soft prefix)
- Decoder:   GPT-2 small (fine-tuned), conditioned on the prefix
- Aux head:  MLP  768 → 2048  (predicts SD3.5 pooled_prompt_embeds)

Training losses
---------------
  L_ce   = cross-entropy on generated tokens vs. original prompt (teacher-forcing)
  L_pool = MSE between predicted and stored SD3.5 pooled_prompt_embeds
  L_total = L_ce + λ_pool * L_pool

The auxiliary loss keeps the shared CLIP feature semantically grounded in
SD3.5's conditioning space. The CE loss teaches the decoder to output fluent,
SD3.5-style prompts. Together they implement a soft round-trip: the decoder
produces text that CLIP associates with the image, while the pooled head
ensures that text also matches SD3.5's own conditioning.

Comparison with SD35ConditioningInverter (models/sd35_inverter.py)
-------------------------------------------------------------------
  SD35ConditioningInverter : image → (pooled_embeds, seq_embeds)  [tensors]
  SD35TextInverter          : image → p*                           [text]

The text inverter is interpretable and validatable (you can read p*),
directly comparable to VLM/PEZ/Z2T, and feeds naturally into the
trajectory experiment (run SD3.5(p*) from the same x_T as the AND run).

The conditioning inverter remains useful for the upper-bound analysis where
no natural-language bottleneck is desired.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import CLIPVisionModel, GPT2LMHeadModel


# ---------------------------------------------------------------------------
# Constants (reuse CLIP preprocessing from sd35_inverter.py)
# ---------------------------------------------------------------------------

CLIP_MEAN  = [0.48145466, 0.4578275,  0.40821073]
CLIP_STD   = [0.26862954, 0.26130258, 0.27577711]
CLIP_SIZE  = 224
POOLED_DIM = 2048   # SD3.5 pooled_prompt_embeds: CLIP-L (768) + CLIP-G (1280)


def make_clip_preprocessor(device: torch.device):
    """Return a callable: (B,3,H,W) float32 [0,1] → (B,3,224,224) CLIP-normalised."""
    mean = torch.tensor(CLIP_MEAN, device=device).view(1, 3, 1, 1)
    std  = torch.tensor(CLIP_STD,  device=device).view(1, 3, 1, 1)

    def preprocess(images: torch.Tensor) -> torch.Tensor:
        x = F.interpolate(images.float(), size=(CLIP_SIZE, CLIP_SIZE),
                          mode="bicubic", align_corners=False).clamp(0.0, 1.0)
        return (x - mean) / std

    return preprocess


# ---------------------------------------------------------------------------
# Prefix mapper
# ---------------------------------------------------------------------------

class PrefixMapper(nn.Module):
    """
    Maps a CLIP CLS feature to n_prefix soft token embeddings for GPT-2.

    Three-layer MLP: clip_dim → 2*clip_dim → n_prefix * gpt_dim
    LayerNorm after the hidden activation for training stability.
    """

    def __init__(self, clip_dim: int, gpt_dim: int, n_prefix: int):
        super().__init__()
        self.n_prefix = n_prefix
        self.gpt_dim  = gpt_dim
        hidden = clip_dim * 2
        self.net = nn.Sequential(
            nn.Linear(clip_dim, hidden),
            nn.GELU(),
            nn.LayerNorm(hidden),
            nn.Linear(hidden, n_prefix * gpt_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (B, clip_dim) → (B, n_prefix, gpt_dim)
        return self.net(x).view(x.shape[0], self.n_prefix, self.gpt_dim)


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class SD35TextInverter(nn.Module):
    """
    Image → natural-language prompt p* inverter for SD3.5.

    Parameters
    ----------
    clip_model_id : str
        HuggingFace model ID for the CLIP ViT backbone (frozen).
    gpt2_model_id : str
        HuggingFace model ID for the GPT-2 text decoder.
    n_prefix : int
        Number of soft prefix tokens prepended to GPT-2 input.
        More tokens give the image richer context; 16 is a good default.
    pool_loss_weight : float
        λ_pool — relative weight of the auxiliary pooled MSE loss vs. CE.
    freeze_clip : bool
        Keep CLIP weights frozen (strongly recommended).
    """

    def __init__(
        self,
        clip_model_id:    str   = "openai/clip-vit-large-patch14",
        gpt2_model_id:    str   = "gpt2",
        n_prefix:         int   = 16,
        pool_loss_weight: float = 0.1,
        freeze_clip:      bool  = True,
        freeze_gpt2:      bool  = False,
    ):
        super().__init__()

        # ---- Frozen CLIP vision backbone ----------------------------------------
        self.clip = CLIPVisionModel.from_pretrained(clip_model_id)
        if freeze_clip:
            for p in self.clip.parameters():
                p.requires_grad_(False)

        clip_dim = self.clip.config.hidden_size   # 768 for ViT-L/14

        # ---- GPT-2 text decoder -------------------------------------------------
        self.gpt2   = GPT2LMHeadModel.from_pretrained(gpt2_model_id)
        gpt_dim     = self.gpt2.config.n_embd    # 768 for gpt2-small

        # Freeze GPT-2 when data is limited (<5K images).
        # The mapper alone (~6M params) is sufficient to steer generation;
        # GPT-2's pretrained language prior handles fluency.
        if freeze_gpt2:
            for p in self.gpt2.parameters():
                p.requires_grad_(False)

        # ---- Prefix mapper: CLIP CLS → GPT-2 prefix tokens ---------------------
        self.mapper = PrefixMapper(clip_dim, gpt_dim, n_prefix)

        # ---- Auxiliary pooled_embeds head ---------------------------------------
        # Predicts SD3.5 pooled_prompt_embeds (2048-dim) from the same CLS feature.
        # Provides a complementary gradient signal: text alone does not constrain
        # the feature to SD3.5's conditioning space, but the MSE on stored
        # pooled_embeds does.
        self.pool_head = nn.Sequential(
            nn.Linear(clip_dim, clip_dim),
            nn.GELU(),
            nn.LayerNorm(clip_dim),
            nn.Linear(clip_dim, POOLED_DIM),
        )

        self.n_prefix        = n_prefix
        self.pool_loss_weight = pool_loss_weight
        self.freeze_gpt2     = freeze_gpt2

    # ---------------------------------------------------------------------------
    def _clip_cls(self, pixel_values: torch.Tensor) -> torch.Tensor:
        """CLIP forward → CLS token feature (B, clip_dim)."""
        # Run CLIP in eval to keep LayerNorm statistics deterministic even when
        # the rest of the model is in train mode (CLIP is frozen anyway).
        with torch.no_grad():
            out = self.clip(pixel_values=pixel_values, return_dict=True)
        return out.last_hidden_state[:, 0].float()   # (B, 768)

    # ---------------------------------------------------------------------------
    def forward(
        self,
        pixel_values:   torch.Tensor,           # (B, 3, 224, 224) CLIP-normalised
        input_ids:      torch.Tensor,           # (B, L) GPT-2 token ids
        attention_mask: torch.Tensor = None,    # (B, L) 1=real token, 0=pad
        target_pooled:  torch.Tensor = None,    # (B, 2048) stored SD3.5 pooled_embeds
    ) -> dict:
        """
        Teacher-forcing forward pass.

        Returns a dict with keys:
            loss, ce_loss, pool_loss, logits
        """
        B = pixel_values.shape[0]

        # 1. CLIP CLS feature (frozen)
        cls = self._clip_cls(pixel_values)                      # (B, clip_dim)

        # 2. Soft prefix tokens
        prefix = self.mapper(cls)                               # (B, n_prefix, gpt_dim)

        # 3. GPT-2 token embeddings for the teacher-forcing input
        tok_emb = self.gpt2.transformer.wte(input_ids)         # (B, L, gpt_dim)

        # 4. Full sequence: [prefix | prompt tokens]
        inputs_embeds = torch.cat([prefix, tok_emb], dim=1)    # (B, n_prefix+L, gpt_dim)

        # 5. Attention mask: attend to all prefix positions + real prompt tokens
        if attention_mask is not None:
            prefix_mask = torch.ones(B, self.n_prefix,
                                     device=pixel_values.device, dtype=torch.long)
            full_mask = torch.cat([prefix_mask, attention_mask], dim=1)
        else:
            full_mask = None

        # 6. GPT-2 forward
        gpt_out = self.gpt2(inputs_embeds=inputs_embeds,
                            attention_mask=full_mask,
                            return_dict=True)
        logits = gpt_out.logits                                 # (B, n_prefix+L, vocab)

        # 7. CE loss ─ predict prompt[i+1] from position (n_prefix + i)
        #    text_logits[:, i, :] predicts input_ids[:, i+1]
        text_logits = logits[:, self.n_prefix:-1].contiguous()  # (B, L-1, vocab)
        text_labels = input_ids[:, 1:].contiguous()             # (B, L-1)

        # Suppress padded label positions
        if attention_mask is not None:
            text_labels = text_labels.masked_fill(
                attention_mask[:, 1:].contiguous() == 0, -100
            )

        ce_loss = F.cross_entropy(
            text_logits.view(-1, text_logits.size(-1)),
            text_labels.view(-1),
            ignore_index=-100,
        )

        # 8. Auxiliary pooled conditioning loss
        pool_loss = torch.zeros(1, device=pixel_values.device, dtype=ce_loss.dtype)
        if target_pooled is not None:
            pred_pooled = self.pool_head(cls)                   # (B, 2048)
            pool_loss   = F.mse_loss(pred_pooled,
                                     target_pooled.to(pred_pooled))

        total_loss = ce_loss + self.pool_loss_weight * pool_loss

        return {
            "loss":      total_loss,
            "ce_loss":   ce_loss,
            "pool_loss": pool_loss,
            "logits":    logits,
        }

    # ---------------------------------------------------------------------------
    @torch.no_grad()
    def generate(
        self,
        pixel_values:   torch.Tensor,   # (B, 3, 224, 224) CLIP-normalised
        tokenizer,
        max_new_tokens: int = 40,
        num_beams:      int = 4,
        **gen_kwargs,
    ) -> list:
        """
        Generate p* text from image(s).

        The CLIP prefix is used as the initial context; GPT-2 then decodes
        autoregressively. Beam search (num_beams=4) is the default; pass
        do_sample=True, temperature=0.8 for stochastic sampling.

        Returns
        -------
        list[str] of length B
        """
        cls    = self._clip_cls(pixel_values)                   # (B, clip_dim)
        prefix = self.mapper(cls)                               # (B, n_prefix, gpt_dim)

        out_ids = self.gpt2.generate(
            inputs_embeds=prefix,
            max_new_tokens=max_new_tokens,
            num_beams=num_beams,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
            **gen_kwargs,
        )
        return [tokenizer.decode(ids, skip_special_tokens=True).strip()
                for ids in out_ids]

    # ---------------------------------------------------------------------------
    @property
    def num_trainable_params(self) -> int:
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    @property
    def num_total_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


# ---------------------------------------------------------------------------
# Loss (standalone, mirrors inversion_loss in sd35_inverter.py)
# ---------------------------------------------------------------------------

def text_inverter_loss(
    pred_pooled:      torch.Tensor,   # (B, 2048)
    target_pooled:    torch.Tensor,   # (B, 2048)
    text_logits:      torch.Tensor,   # (B, L-1, vocab)
    text_labels:      torch.Tensor,   # (B, L-1) with -100 at pads
    pool_loss_weight: float = 0.1,
) -> dict:
    """
    Compute the two-term training loss.

    This mirrors the forward() internals but is exposed as a standalone
    function so it can be called from custom training loops.
    """
    ce_loss   = F.cross_entropy(
        text_logits.contiguous().view(-1, text_logits.size(-1)),
        text_labels.contiguous().view(-1),
        ignore_index=-100,
    )
    pool_loss = F.mse_loss(pred_pooled, target_pooled.to(pred_pooled))

    with torch.no_grad():
        cos = F.cosine_similarity(pred_pooled, target_pooled.to(pred_pooled), dim=-1).mean()

    total = ce_loss + pool_loss_weight * pool_loss
    return {
        "total":      total,
        "ce_loss":    ce_loss,
        "pool_loss":  pool_loss,
        "pooled_cos": cos,
    }


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------

def save_text_inverter(model: SD35TextInverter, path: str):
    torch.save({
        "state_dict":       model.state_dict(),
        "n_prefix":         model.n_prefix,
        "pool_loss_weight": model.pool_loss_weight,
        "freeze_gpt2":      model.freeze_gpt2,
    }, path)


def load_text_inverter(
    path:          str,
    clip_model_id: str          = "openai/clip-vit-large-patch14",
    gpt2_model_id: str          = "gpt2",
    device:        torch.device = torch.device("cpu"),
) -> SD35TextInverter:
    ckpt  = torch.load(path, map_location=device, weights_only=True)
    model = SD35TextInverter(
        clip_model_id    = clip_model_id,
        gpt2_model_id    = gpt2_model_id,
        n_prefix         = ckpt.get("n_prefix", 16),
        pool_loss_weight = ckpt.get("pool_loss_weight", 0.1),
        freeze_gpt2      = ckpt.get("freeze_gpt2", False),
    )
    model.load_state_dict(ckpt["state_dict"])
    return model.to(device)
